apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: secretservice
  name: secretservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secretservice
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: secretservice
    spec:
      volumes:
      - name: secret-service-volume
        secret: 
          secretName: my-secrets
      containers:
      - image: alpine
        name: alpine
        command: ['sleep', '600']
        volumeMounts:
        - name: secret-service-volume
          mountPath: /etc/users
