apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: probe-pod
  name: probe-pod
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
      - containerPort: 80
    resources: {}
  - image: busybox
    name: busybox
    command: ["sleep", "3600"]
    readinessProbe:
      initialDelaySeconds: 10
      periodSeconds: 10
      tcpSocket: 
        port: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
