apiVersion:  extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: hostname.nginx
  - http:
      paths:
      - path: /nginx
        pathType: Prefix
        backend:
          serviceName: nginx 
          servicePort: 80
