apiVersion: v1
kind: Service
metadata:
  labels:
    app: proxy
    manager: kubectl-edit
    operation: Update
  name: nginx
  namespace: default
spec:
  clusterIP: 10.102.185.140
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32000
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: proxy
  sessionAffinity: None
  type: NodePort
