apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-02-19T04:31:08Z"
  labels:
    app: proxy
    manager: kubectl-expose
    operation: Update
  name: nginx-lab7
  namespace: default
  resourceVersion: "3819"
spec:
  clusterIP: 10.102.185.140
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: proxy
  sessionAffinity: None
  type: ClusterIP
